### ISSUE TITLE
The website is down 

### ISSUE THREAD

**Issue by Bijit-Mondal** [vuesax-alpha/vuesax-alpha#1]
Make the website up and work on https

**Comment by tranthinh-coding** [comment]
Sorry, I just passed an exam so I can't work it🥲. Around 01/04, I'll continue to maintain this project and push the documentation page up. 

Here is the version that works with Vue 3. But most of the api from the old version is still working. You can test with the api through the documentation of [Vuesax](https://vuesax.com)
