### ISSUE TITLE
Update time inquiry

### ISSUE THREAD

**Issue by Anan-GitHub** [vuesax-alpha/vuesax-alpha#17]
Hello, I am a backend java developer, I really like this set of vue3 related components, but the notification feature is not available yet, the notification menu on the official website is 404, when will it be updated to support notification feature in vue3? I'm very sorry for my limited level of front-end development, I can't offer to help front-end developers!

**Comment by tranthinh-coding** [comment]
Oh sorry, I forgot to update the documentation to the latest version.
However, you can go to the Preview page to preview.Its here
https://vuesax-alpha-docs-bu3v1cfl9-tranthinh-coding.vercel.app/components/notification.html
.
Thanks ❤

Vào 15:43, T.5, 20 Th7, 2023 Anan-GitHub ***@***.***> đã viết:

**Comment by Anan-GitHub** [comment]
> 哦抱歉，我忘了将文档更新到最新版本。不过，您可以进入预览页面进行预览。它在这里 https://vuesax-alpha-docs-bu3v1cfl9-tranthinh-coding.vercel.app/components/notification.html



> 哦抱歉，我忘了将文档更新到最新版本。不过，您可以进入预览页面进行预览。它在这里 https://vuesax-alpha-docs-bu3v1cfl9-tranthinh-coding.vercel.app/components/notification.html



> 哦抱歉，我忘了将文档更新到最新版本。不过，您可以进入预览页面进行预览。它在这里 https://vuesax-alpha-docs-bu3v1cfl9-tranthinh-coding.vercel.app/components/notification.html

Ok, thank you very much, love the components you have developed, very nice, thanks!
