### ISSUE TITLE
VsLoadingFn error.

### ISSUE THREAD

**Issue by HaroldLoui** [vuesax-alpha/vuesax-alpha#20]
Hi, I got an error when used the VsLoadingFn. The version of alpha is `^0.2.0-beta.39`, just install with `npm install vuesax-alpha`.

![image](https://github.com/vuesax-alpha/vuesax-alpha/assets/63445267/721e0770-f371-4294-a2d6-470d2758ba08)

```html
<div ref="captchaDom" class="validate-code-image">
    <img :src="captchaCode" @click="getCaptcha" />
</div>
```

```js
import { ref, reactive, onMounted } from "vue";
import { VsLoadingFn } from "vuesax-alpha";

const captchaCode = ref("");
const captchaDom = ref<HTMLElement>();

onMounted(() => {
  getCaptcha();
});
const getCaptcha = () => {
  const loadingInstance = VsLoadingFn({
    target: captchaDom,
  });
  captcha()
    .then((res) => {
      captchaCode.value = res.data.image;
    })
    .catch((err) => {
      console.log(err);
    })
    .finally(() => {
      loadingInstance.close();
    });
};
```

**Comment by HaroldLoui** [comment]
![image](https://github.com/vuesax-alpha/vuesax-alpha/assets/63445267/ea2ec211-a1cc-4107-9cbc-2f53ea13a84d)

 And there is an error message: Module '"vuesax-alpha"' has no exported member 'VsLoadingFn'. Did you mean to use 'import VsLoadingFn from "vuesax-alpha"' instead?ts(2614)

**Comment by tranthinh-coding** [comment]
Thanks for reporting the error.
I fixed it and released version `v0.2.0-beta.40`.
Let's try it <3

**Comment by tranthinh-coding** [comment]
> ![image](https://user-images.githubusercontent.com/63445267/258959172-ea2ec211-a1cc-4107-9cbc-2f53ea13a84d.png)
> 
> And there is an error message: Module '"vuesax-alpha"' has no exported member 'VsLoadingFn'. Did you mean to use 'import VsLoadingFn from "vuesax-alpha"' instead?ts(2614)

If you use volar, please add the global component type definition to compilerOptions.types in tsconfig.json.

```json
// tsconfig.json
{
  "compilerOptions": {
    // ...
    "types": ["vuesax-alpha/global"]
  }
}
```

**Comment by HaroldLoui** [comment]
> > ![image](https://user-images.githubusercontent.com/63445267/258959172-ea2ec211-a1cc-4107-9cbc-2f53ea13a84d.png)
> > And there is an error message: Module '"vuesax-alpha"' has no exported member 'VsLoadingFn'. Did you mean to use 'import VsLoadingFn from "vuesax-alpha"' instead?ts(2614)
> 
> If you use volar, please add the global component type definition to compilerOptions.types in tsconfig.json.
> 
> ```json
> // tsconfig.json
> {
>   "compilerOptions": {
>     // ...
>     "types": ["vuesax-alpha/global"]
>   }
> }
> ```

Thanks. Vuesax is very nice and beautiful UI framework!!!

**Comment by JesusFregoso** [comment]
vs-rate documentation is missing the code example

**Comment by tranthinh-coding** [comment]
> vs-rate documentation is missing the code example

ok i'll update soon
