### ISSUE TITLE
vue-vite  ’pnpm‘安装后  无法解析vuesax

### ISSUE THREAD

**Issue by YourCueCat** [vuesax-alpha/vuesax-alpha#24]
使用的是  vue vite  
’pnpm‘安装后 
main.js
import Vuesax from 'vuesax-alpha'

出现问题 无法解析vuesax
Failed to resolve entry for package "vuesax-alpha". 
The package may have incorrect main/module/exports specified in its package.json.

**Comment by tranthinh-coding** [comment]
which version are you using?

**Comment by tranthinh-coding** [comment]
can you provide a mini repo on stackblitz

**Comment by YourCueCat** [comment]
好的 问题是一样复现的 我不知道是否是我操作问题  https://stackblitz.com/edit/vitejs-vite-xso3gz
