### ISSUE TITLE
vuesax.space   Homepage display small issue

### ISSUE THREAD

**Issue by YourCueCat** [vuesax-alpha/vuesax-alpha#25]
vuesax.space     Individual components (on demand)  
官网文档有点问题
correct：    import { VsInput, VsButton }  from 'vuesax-alpha'
按需要引入  组件的首字母  正确的应该是大写  V

error：    import { vsAlert, vsInput, vsPopup } from 'vuesax-alpha'
vuesax.space  官网的小写v是无法引入的 v

**Comment by tranthinh-coding** [comment]
Can you create a pull request to fix this?
