### ISSUE TITLE
How use components like vs-popper, vs-scrollbar, vs-chip, etc??

### ISSUE THREAD

**Issue by lrferreiro** [vuesax-alpha/vuesax-alpha#27]
I have tried to use some components but I have not been able to use them. Can they be used?

**Comment by tranthinh-coding** [comment]
The scrollbar and popper components might work fine. I'll update the documentation for these components soon. For the VsChip component, it still doesn't work.

**Comment by tranthinh-coding** [comment]
I have updated the documentation for the scrollbar component.
As for the popper component, it will be considered for export in the next version

**Comment by lrferreiro** [comment]
Thank you, I am very happy to be able to use these components, because I needed to be able to make a phone field. Without a doubt, the best of the best. I hope later you can incorporate others such as: textarea, link, etc.

**Comment by tranthinh-coding** [comment]
thanks for your suggestion
