### ISSUE TITLE
Tooltip will exceed the screen at the edge BUG

### ISSUE THREAD

**Issue by Anan-GitHub** [vuesax-alpha/vuesax-alpha#32]
Hello, the tool tip may exceed the screen range at the edge. Can this issue be fixed? thanks

<img width="466" alt="iShot_2023-09-15_19 53 02" src="https://github.com/vuesax-alpha/vuesax-alpha/assets/67733882/9906888f-788e-4439-a138-fa875133bd1e">

**Comment by Anan-GitHub** [comment]
Each blue square needs to be prompted by clicking, and when the square at the edge of the screen is clicked, the tool prompt will go beyond the screen. hope to be able to adapt to the screen edges so that the controls can truly be used. Thank you very much

<img width="1679" alt="iShot_2023-09-15_20 05 20" src="https://github.com/vuesax-alpha/vuesax-alpha/assets/67733882/6bc7c501-8153-40dc-9f04-cbce85a04f8e">

**Comment by Anan-GitHub** [comment]
@tranthinh-coding Hello, can this bug be resolved? Which version will probably solve it? I want to use this Tooltip control, but this bug cannot achieve the desired effect. I want to be able to adapt to the screen edges. Thank you~

**Comment by tranthinh-coding** [comment]
oh sorry, I forgot about this. I will process and release the latest version before November 5

**Comment by tranthinh-coding** [comment]
Sorry, I'm working on a commercial project so I can't focus on processing it. In the meantime I suggest you use the floating-ui/vue package to create tooltips, as I will be building on top of this package.

**Comment by Anan-GitHub** [comment]
Received, thank you
