### ISSUE TITLE
[Sidebar] No relative props

### ISSUE THREAD

**Issue by aomKorawit** [vuesax-alpha/vuesax-alpha#33]
vs-sidebar does not have relative props

<img width="260" alt="image" src="https://github.com/vuesax-alpha/vuesax-alpha/assets/16049010/8fae31e3-77f0-45a8-87f5-e404bdc23ca5">

<img width="513" alt="image" src="https://github.com/vuesax-alpha/vuesax-alpha/assets/16049010/4bffc7f1-9edd-4614-9cd8-b7e09538403d">

**Comment by tranthinh-coding** [comment]
oh sorry, it is `absolute`, not `relative`
