### ISSUE TITLE
[BUG] VsLoadingFn target no effect

### ISSUE THREAD

**Issue by serious-snow** [vuesax-alpha/vuesax-alpha#36]
loading show in fullscreen.

`  <div ref="$content" style="width: 100px;height: 100px">test</div>`

```
const $content=ref()
const loadingInstance = VsLoadingFn({
  target: $content,
})
setTimeout(()=>{
  loadingInstance.close()
},1000*10)```

**Comment by tranthinh-coding** [comment]
Let's call function VsLoadingFn inside onMounted hook or after DOM mounted so it works fine

**Comment by tranthinh-coding** [comment]
In the next release, it will be tweaked a bit to be able to track target changes.

**Comment by serious-snow** [comment]
thanks. Do you have any plans to add components, such as Tab?

**Comment by tranthinh-coding** [comment]
> thanks. Do you have any plans to add components, such as Tab?

Of course
it will be released in v1.x.x
