### ISSUE TITLE
Support new icon component in VS-Notification

### ISSUE THREAD

**Issue by Hooper93** [vuesax-alpha/vuesax-alpha#37]
the demo code on document is not work.
```js
return VsNotification({
            icon: `<i class='bx bxs-time'></i>`,
            color: 'primary',
            position: 'top-right',
```
every where I use icon, is 
```js
import * as VuesaxAlphaIconsVue from '@vuesax-alpha/icons-vue'
XXXXX
```

**Comment by Hooper93** [comment]
I try
```js
import {Bell} from '@vuesax-alpha/icons-vue'
return VsNotification({
            icon: Bell,
            color: 'primary',
```
than get:
![image](https://github.com/vuesax-alpha/vuesax-alpha/assets/48215196/0d1f86a7-6149-41b9-81d5-d7d86fa1dffb)

how can I modify icon size? write a single icon component and import it?  That's too much trouble. 

sad

**Comment by tranthinh-coding** [comment]
icon: `<i class='bx bxs-time'></i>`

I see you are using [boxicons](https://boxicons.com/), have you installed it yet?

**Comment by tranthinh-coding** [comment]
thanks
u can change the icon size or pass an icon component via props  in the next versions.

Do u have any more suggestions?

**Comment by Hooper93** [comment]
I installed [boxicons](https://boxicons.com/), and now it works fine for me. 🎉
and support '@vuesax-alpha/icons-vue' is also necessary.
Very nice work，and I'll be looking forward to your new work ~
