### ISSUE TITLE
[bug] Select drop-box will shift as the page scrolls

### ISSUE THREAD

**Issue by little-buddy** [vuesax-alpha/vuesax-alpha#38]
<img width="397" alt="image" src="https://github.com/vuesax-alpha/vuesax-alpha/assets/30054881/7c697778-2c97-41f0-ab33-50ed6b543e8f">

**Comment by tranthinh-coding** [comment]
Which version are you using?

**Comment by little-buddy** [comment]
vuesax-alpha@v0.2.0-beta.62
vue@3.3.7
