### ISSUE TITLE
https Certificate Error

### ISSUE THREAD

**Issue by silite** [vuesax-alpha/vuesax-alpha#40]
<img width="716" alt="image" src="https://github.com/vuesax-alpha/vuesax-alpha/assets/32181762/86ae6fa7-9585-41f2-ace9-1cc214ab50b8">

**Comment by tranthinh-coding** [comment]
Sorry, the domain has expired and I forgot to renew it. Please visit this [link](https://vuesax-alpha.vercel.app/)
