### ISSUE TITLE
The official website has expired and cannot be accessed. An icon is required

### ISSUE THREAD

**Issue by Anan-GitHub** [vuesax-alpha/vuesax-alpha#41]
Hello, official website https://www.vuesax.space/ Unable to access, I want to use icon. I previously provided a preview website https://vuesax-alpha-docs-bu3v1cfl9-tranthinh-coding.vercel.app But there is no icon inside

**Comment by tranthinh-coding** [comment]
Hi, Sorry, the domain has expired but I forgot to renew it. Please visit this [link](https://vuesax-alpha.vercel.app/)

**Comment by Anan-GitHub** [comment]
Received, thank you
