### ISSUE TITLE
Type of loading isn't working

### ISSUE THREAD

**Issue by Bijit-Mondal** [vuesax-alpha/vuesax-alpha#42]
In javascript (not using typescript) vsLoading type instance not working

**Comment by tranthinh-coding** [comment]
Can you describe more clearly? send me the code you use

**Comment by Bijit-Mondal** [comment]
```
loadingInstance = VsLoadingFn({
      type: 'wave',
      color: '#5b3cc4',
      background: '#1e2023',
   });
```
        
In this code a loading overlay is coming but wave is not coming in the loading

**Comment by tranthinh-coding** [comment]
```js
loadingInstance = VsLoadingFn({
      type: 'waves', // instead of `wave`
      color: '#5b3cc4',
      background: '#1e2023',
   });
```

please try **waves** instead of **wave**

**Comment by Bijit-Mondal** [comment]
yes, I have tried But still it's not working,

**Comment by tranthinh-coding** [comment]
thanks, let me check again

**Comment by Bijit-Mondal** [comment]
```
import { VsLoadingFn } from 'vuesax-alpha'

let loadingInstance;

export const loadingService = {
    show: function(){
        loadingInstance = VsLoadingFn({
            type: 'waves',
            color: '#5b3cc4',
            background: '#1e2023',
        });
    },
    hide: function(){
        loadingInstance.close();
    }
}
```

This is my  loading service and I am using it in 
```
created() {
    loadingService.show();
  },
  ```
  
  It is just showing the overlay of the background color I have specified

**Comment by tranthinh-coding** [comment]
I just tested your code, it still runs normally, the problem is because the background and color are too similar

**Comment by Bijit-Mondal** [comment]
Yeah, my fault. Thank you

**Comment by tranthinh-coding** [comment]
Do you see any warnings appearing in the console when using LoadingFn?
