### ISSUE TITLE
fix:(vs-select): fixed width vs-select__content 

### ISSUE THREAD

**Issue by mpashaa** [vuesax-alpha/vuesax-alpha#44]
Hello! Please tell me why you decided to add a fixed width of 200 pixels for the content vs-select?

![image](https://github.com/vuesax-alpha/vuesax-alpha/assets/84025252/5f33fe50-9987-4f58-99f6-0c038c34e6d0)

Commit: https://github.com/vuesax-alpha/vuesax-alpha/commit/a7b70a18d15e9739d24df294a8b102fbd82010f1
File: packages/theme-chalk/src/select.scss

Because of this, a problem arose if the vs-select is not equal to 200 pixels

![image](https://github.com/vuesax-alpha/vuesax-alpha/assets/84025252/1893860e-c067-476b-8154-e3e01b5cdb76)

![image](https://github.com/vuesax-alpha/vuesax-alpha/assets/84025252/199564c0-97b1-4f54-86ac-97add265f009)

**Comment by tranthinh-coding** [comment]
Sorry, it's just temporary. I forgot to fix it. I will release a new version tonight

**Comment by mpashaa** [comment]
> Извините, это временно. Я забыл это исправить. сегодня вечером выложу новую версию

Thank you

**Comment by tranthinh-coding** [comment]
sorry i'm late, please test for me <3
