### ISSUE TITLE
When operating, the prompt module "vuesax alpha" does not have an exported member "VsLoadingFn". Do you want to use "import VsLoadingFn from" vuesax alpha "instead? How to solve the problem of inability to compile

### ISSUE THREAD

**Issue by uxiaohan** [vuesax-alpha/vuesax-alpha#48]
In the Vue3.4.15+Ts5.3.0 project,<script lang="ts" setup>
Import {VsLoadingFn} from 'vuesax alpha';
</script>
When operating, the prompt module "vuesax alpha" does not have an exported member "VsLoadingFn". Do you want to use "import VsLoadingFn from" vuesax alpha "instead? How to solve the problem of inability to compile

**Comment by tranthinh-coding** [comment]
What version of vuesax-alpha are you using?

Is the library name you used correct? -> "vuesax-alpha"

**Comment by uxiaohan** [comment]
I'm using "vuesax-alpha": "0.2.0-beta.73",
There is no problem with referenced names, my current solution is in
Add export {VsNotification, VsLoadingFn} from 'vuesax-alpha'; in 
\node_modules\.pnpm\vuesax-alpha@0.2.0-beta.73_vue@3.4.19\node_modules\vuesax-alpha\es\index.d.ts
to solve the problem

![image](https://github.com/vuesax-alpha/vuesax-alpha/assets/29017861/d25dd4db-d84a-4b22-b542-aa62da545173)

**Comment by tranthinh-coding** [comment]
thanks, lets me check again

**Comment by uxiaohan** [comment]
Have you found the problem, or is it just my personal problem?

**Comment by badspider7** [comment]
i have the same problem in VsNotification.

**Comment by tranthinh-coding** [comment]
Thanks, let's try to change *compilerOptions.moduleResolution* to **node** in tsconfig.json


this is my tsconfig.json
```json
{
  "compilerOptions": {
    ...
    "moduleResolution": "node",
    "types": ["vuesax-alpha/global"]
  }
}
```

**Comment by uxiaohan** [comment]
According to your plan, reinstall the dependencies, clear the cache, and still do so，Module 'vuesax alpha' does not have an exported member 'VsNotification'. Do you want to use "import VsNotification from" vuesax alpha "instead? Ts plugin (2614)

**Comment by tranthinh-coding** [comment]
> According to your plan, reinstall the dependencies, clear the cache, and still do so，Module 'vuesax alpha' does not have an exported member 'VsNotification'. Do you want to use "import VsNotification from" vuesax alpha "instead? Ts plugin (2614)

try changing _compilerOptions.moduleResolution_ to _node_ in your tsconfig.json

**Comment by tranthinh-coding** [comment]
> Thanks, let's try to change _compilerOptions.moduleResolution_ to **node** in tsconfig.json
> 
> this is my tsconfig.json
> 
> ```json
> {
>   "compilerOptions": {
>     ...
>     "moduleResolution": "node",
>     "types": ["vuesax-alpha/global"]
>   }
> }
> ```

like this

**Comment by uxiaohan** [comment]
"compilerOptions": {
    "composite": true,
    "noEmit": true,
    "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.node.tsbuildinfo",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "types": ["node", "vuesax-alpha/global"]
  }
This is my configuration. If it is based on your configuration, it may cause some dependencies to not work properly. Is there a better solution? There is also an issue. When using the VsNotification component, the prompt content passed in is not invalid, but content is the content. However, the example is indeed text. Please update it

**Comment by tranthinh-coding** [comment]
can you provide a small repo

**Comment by badspider7** [comment]
When I recreated a demo project, notification was normal, but there were other TS errors
![image](https://github.com/vuesax-alpha/vuesax-alpha/assets/54093230/6ce0d168-93ac-45bf-bfbe-8e00e60e4024)

**Comment by tranthinh-coding** [comment]
> When I recreated a demo project, notification was normal, but there were other TS errors ![image](https://private-user-images.githubusercontent.com/54093230/309789597-6ce0d168-93ac-45bf-bfbe-8e00e60e4024.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NjM4MTUsIm5iZiI6MTcwOTU2MzUxNSwicGF0aCI6Ii81NDA5MzIzMC8zMDk3ODk1OTctNmNlMGQxNjgtOTNhYy00NWJmLWJmYmUtOGUwMGU2MGU0MDI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDE0NDUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2M2M0OWIwYjQ2YzhkNGZhODNmODMzOWM0ZjIxMjlkNjcwZTMwYjNhNjM5YTA1ZmUxYTdhNzVmNzQzNTU1ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5KcVZ80o1BEd7ZGbrVMpLSch7Wipg7Id6zizp7H7Mds)

in new version, i remove prop text, using content instead, cause it render to the same position

**Comment by badspider7** [comment]
ok

**Comment by tranthinh-coding** [comment]
Is this issue been resolved?
