### ISSUE TITLE
Docs:document  api property click event error

### ISSUE THREAD

**Issue by badspider7** [vuesax-alpha/vuesax-alpha#58]
When I just click on an example property  of the document API, all open properties will be displayed copied.I think is not a bug in vuesax-alpha,but i found it.So I brought it up😺
![image](https://github.com/vuesax-alpha/vuesax-alpha/assets/54093230/97465190-1e4a-4577-bd37-30ca0bbe438d)

**Comment by tranthinh-coding** [comment]
That's the feature 👀

**Comment by badspider7** [comment]
Okay, I misunderstood, hahaha🥳

**Comment by tranthinh-coding** [comment]
i'll fix it soon. Currently I'm refactoring the table component:<

**Comment by badspider7** [comment]
ok，i  will try to see this .Although I am a front-end novice.Thank you for your reply

**Comment by badspider7** [comment]
i fix it🥳
