### ISSUE TITLE
a icon error

### ISSUE THREAD

**Issue by nice2cu1** [vuesax-alpha/vuesax-alpha#76]
border star icon name have a error

![image](https://github.com/vuesax-alpha/vuesax-alpha/assets/33564254/1ac42177-23bd-4d4b-b44a-e3a4d96fcf1c)

**Comment by badspider7** [comment]
can you show me the code

**Comment by nice2cu1** [comment]
no code,when I click border star icon, I got this code `<vs-icon><Start /></vs-icon>`
it shouldn't be **_Start_**, it's **_Star_**

**Comment by badspider7** [comment]
ok,i got it😺
