### ISSUE TITLE
[vs-select] - Maximum recursive updates exceeded in component <BaseTransition>

### ISSUE THREAD

**Issue by mpashaa** [vuesax-alpha/vuesax-alpha#78]
Hi. An error occurred while searching in the vs-select component. I have a country directory that contains 250 vs-option.

```
<vs-select v-model="filter.country" filter label="Geo" placeholder="Geo">
  <vs-option
    v-for="country in options.countries"
    :key="country.id"
    :label="country.en_name"
    :value="country.id"
  />
</vs-select>

```
When searching for a country, this error occurs:
![image](https://github.com/vuesax-alpha/vuesax-alpha/assets/84025252/88fa0d9c-294d-4a20-b093-36bcadffc67e)

After this error, it is impossible to close the country selection vs-popper
![image](https://github.com/vuesax-alpha/vuesax-alpha/assets/84025252/b8b9b556-4c76-40d4-9e85-6c2b8d56da54)

**Comment by mpashaa** [comment]
List of countries I use [countries.json](https://github.com/user-attachments/files/15986067/countries.json). If you leave 99 countries from this list, the problem will disappear

**Comment by tranthinh-coding** [comment]
Thanks, i'll try it

**Comment by mpashaa** [comment]
The error disappeared after I switched from vue v3.4.30 to v3.2.47. Thanks
