### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by Inseparable-Bird** [vuesax-alpha/vuesax-alpha#81]
Hi! I want to change the font, but I found that all the font styles have been added! important， This makes it difficult for me to replace globally. If possible, I hope to have a global configuration function, such as rounded corners, font styles, font sizes, and so on

**Comment by badspider7** [comment]
Is there a problem with which component? Can you provide me with your code.

When  <style> tag has the scoped attribute,you can use `:deep()` to slove this problem.

[Deep Selectors](https://vuejs.org/api/sfc-css-features.html#deep-selectors)
> If possible, I hope to have a global configuration function, such as rounded corners, font styles, font sizes, and so on

This is indeed a good suggestion, we will refer to it in the future.
