### ISSUE TITLE
复选框警告问题

### ISSUE THREAD

**Issue by Inseparable-Bird** [vuesax-alpha/vuesax-alpha#82]
![image](https://github.com/user-attachments/assets/d5570d99-b824-4352-92bb-d0f447198389)
![image](https://github.com/user-attachments/assets/3cdd8eca-57f2-4758-b155-37a0781fa7d0)
每次点击的时候都会报这个警告

**Comment by badspider7** [comment]
已经修复了，到时候更新看看
