### ISSUE TITLE
输入框样式问题

### ISSUE THREAD

**Issue by Inseparable-Bird** [vuesax-alpha/vuesax-alpha#85]
![image](https://github.com/user-attachments/assets/d9a39a58-2b5f-49a6-98ca-d085197a8013)
![image](https://github.com/user-attachments/assets/758a301d-8d85-43b0-a57f-7c1f71a3bc7f)
使用数字类型输入框可以输入字母并且会出现样式问题

**Comment by Inseparable-Bird** [comment]
![image](https://github.com/user-attachments/assets/ad862aa5-f2aa-4ebe-8303-32043850b0cb)
输入框为disabled的时候字体颜色没有置灰ಠ_ಠ

**Comment by badspider7** [comment]
你好,关于上面的问题。

1.样式的问题正在修复中；

2.那个type=number 能输入e 是因为在数学里e 代表无理数，e是自然对数的底数，所以在输入 e 时，输入框会默认 e 是数字，从而没有对它进行限制；

3.我看输入框好像没有disabled这个属性。
