### ISSUE TITLE
[Icons] - Icons，size does not work

### ISSUE THREAD

**Issue by ppc-chen822** [vuesax-alpha/vuesax-alpha#87]
**Steps to Reproduce**
In the reference icons code as follows, size does not work, how to change its color?
![image](https://github.com/user-attachments/assets/dd594441-83f9-4ce0-859a-c8f20f60ac7d)
![image](https://github.com/user-attachments/assets/4515c707-6887-4ab9-8012-94f1e560a0a0)

**Comment by tranthinh-coding** [comment]
you can pass prop `color` into `vs-icon` component. The `color` accepted vuesax's color, hex or rgb.

**Comment by tranthinh-coding** [comment]
i see prop `size` work correctly, can you provide more infor? Which version of vuesax-alpha?
